// Code generated by cmd/reset; DO NOT EDIT.

package storage

// Reset resets all fields of UserURL to zero values.
func (r *UserURL) Reset() {
	if r == nil {
		return
	}
	r.ShortURL = ""
	r.OriginalURL = ""
}
