// Package main is a utility for generating Reset() methods for struct types
// tagged with // generate:reset.
//
// The generator scans all packages in the project and generates a Reset()
// method for each struct with the // generate:reset comment, resetting
// fields to their zero values:
//
//   - primitives (int, string, bool) → zero values
//   - slices → [:0] (truncate without nil)
//   - maps → clear()
//   - pointers to primitives → nil check + reset value
//   - nested structs with Reset() → call Reset()
//
// Generated methods are written to reset.gen.go in the source package.
//
// Usage:
//
//	go run ./cmd/reset/...
package main

import (
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const resetTag = "generate:reset"

// structInfo holds information about a struct for Reset() generation.
type structInfo struct {
	name   string
	fields []fieldInfo
}

// fieldInfo holds information about a struct field.
type fieldInfo struct {
	name string
	typ  types.Type
}

func main() {
	if err := run(); err != nil {
		log.Fatalf("error: %v\n", err)
	}
}

func run() error {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
			packages.NeedTypes | packages.NeedTypesInfo | packages.NeedTypesSizes,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return fmt.Errorf("load packages: %w", err)
	}

	packages.PrintErrors(pkgs)

	for _, pkg := range pkgs {
		if pkg.Name == "main" {
			continue
		}

		structs := collectStructs(pkg)
		if len(structs) == 0 {
			continue
		}

		if err := writeResetFile(pkg, structs); err != nil {
			return fmt.Errorf("write reset file for %s: %w", pkg.PkgPath, err)
		}
		fmt.Printf("generated %s/reset.gen.go (%d structs)\n", pkg.PkgPath, len(structs))
	}

	return nil
}

// collectStructs finds all structs with the // generate:reset tag in a package.
func collectStructs(pkg *packages.Package) []structInfo {
	var result []structInfo

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			// GenDecl.Doc contains comments directly before the type declaration.
			// This is the most reliable way to associate comments with declarations.
			if genDecl.Doc == nil || !hasResetTag(genDecl.Doc) {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || typeSpec.Type == nil {
					continue
				}

				if _, ok = typeSpec.Type.(*ast.StructType); !ok {
					continue
				}

				fields := collectFieldsFromAST(typeSpec, pkg.TypesInfo)
				if len(fields) > 0 {
					result = append(result, structInfo{
						name:   typeSpec.Name.Name,
						fields: fields,
					})
				}
			}
		}
	}

	sort.Slice(result, func(i, j int) bool {
		return result[i].name < result[j].name
	})

	return result
}

// hasResetTag checks if an ast.CommentGroup contains the // generate:reset tag.
func hasResetTag(doc *ast.CommentGroup) bool {
	for _, comment := range doc.List {
		text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
		if text == resetTag {
			return true
		}
	}
	return false
}

// collectFieldsFromAST collects struct fields from AST + types.Info.
func collectFieldsFromAST(typeSpec *ast.TypeSpec, info *types.Info) []fieldInfo {
	var fields []fieldInfo
	structType, ok := typeSpec.Type.(*ast.StructType)
	if !ok {
		return nil
	}
	for _, field := range structType.Fields.List {
		if field.Names == nil {
			continue
		}
		for _, name := range field.Names {
			typ := info.TypeOf(name)
			fields = append(fields, fieldInfo{
				name: name.Name,
				typ:  typ,
			})
		}
	}
	return fields
}

// writeResetFile generates and writes reset.gen.go.
func writeResetFile(pkg *packages.Package, structs []structInfo) error {
	var sb strings.Builder

	sb.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", pkg.Name))

	for _, s := range structs {
		sb.WriteString(generateResetMethod(s))
	}

	genFile := filepath.Join(pkg.Dir, "reset.gen.go")
	return os.WriteFile(genFile, []byte(sb.String()), 0644)
}

// generateResetMethod generates the Reset() method for a struct.
func generateResetMethod(s structInfo) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("// Reset resets all fields of %s to zero values.\n", s.name))
	sb.WriteString(fmt.Sprintf("func (r *%s) Reset() {\n", s.name))
	sb.WriteString("\tif r == nil {\n\t\treturn\n\t}\n")

	for _, f := range s.fields {
		sb.WriteString(generateFieldReset(f))
	}

	sb.WriteString("}\n")
	return sb.String()
}

// generateFieldReset generates the reset code for a single field.
func generateFieldReset(f fieldInfo) string {
	switch t := f.typ.(type) {
	case *types.Basic:
		switch t.Kind() {
		case types.String:
			return fmt.Sprintf("\tr.%s = \"\"\n", f.name)
		case types.Bool:
			return fmt.Sprintf("\tr.%s = false\n", f.name)
		default:
			return fmt.Sprintf("\tr.%s = 0\n", f.name)
		}
	case *types.Slice:
		return fmt.Sprintf("\tr.%s = r.%s[:0]\n", f.name, f.name)
	case *types.Map:
		return fmt.Sprintf("\tclear(r.%s)\n", f.name)
	case *types.Pointer:
		elem := t.Elem()
		switch elem := elem.(type) {
		case *types.Basic:
			var zero string
			switch elem.Kind() {
			case types.String:
				zero = "\"\""
			case types.Bool:
				zero = "false"
			default:
				zero = "0"
			}
			return fmt.Sprintf("\tif r.%s != nil {\n\t\t*r.%s = %s\n\t}\n", f.name, f.name, zero)
		case *types.Struct:
			return fmt.Sprintf("\tif r.%s != nil {\n\t\tr.%s.Reset()\n\t}\n", f.name, f.name)
		default:
			return fmt.Sprintf("\tif r.%s != nil {\n\t\tr.%s = nil\n\t}\n", f.name, f.name)
		}
	default:
		return ""
	}
}
