// Code generated by cmd/reset; DO NOT EDIT.

package audit

// Reset resets all fields of Event to zero values.
func (r *Event) Reset() {
	r.Timestamp = 0
	r.Action = ""
	r.UserID = ""
	r.URL = ""
}
