// Code generated by cmd/reset; DO NOT EDIT.

package config

// Reset resets all fields of Config to zero values.
func (r *Config) Reset() {
	if r == nil {
		return
	}
	r.Host = ""
	r.BaseURL = ""
	r.FilePath = ""
	r.DB = ""
	r.AuthSecret = ""
	r.WorkerBufferSize = 0
	r.AuditFile = ""
	r.AuditURL = ""
	r.StoreType = ""
}
